services:
    mongo:
        image: mongo:7
        ports:
            - '27017:27017'

    redis:
        image: redis
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        ports:
            - '6379:6379'
