export const users = [
    {
        name: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        password: 'password123',
        createdAt: new Date('2024-01-01'),
        updatedAt: null,
        deletedAt: null,
        role: 'user',
    },
    {
        name: 'Bob Smith',
        email: 'bob.smith@example.com',
        password: 'securepass456',
        createdAt: new Date('2024-01-02'),
        updatedAt: null,
        deletedAt: null,
        role: 'admin',
    },
    {
        name: 'Charlie Evans',
        email: 'charlie.evans@example.com',
        password: 'mypassword789',
        createdAt: new Date('2024-01-03'),
        updatedAt: null,
        deletedAt: null,
        role: 'user',
    },
    {
        name: 'Diana Parker',
        email: 'diana.parker@example.com',
        password: 'strongpass101',
        createdAt: new Date('2024-01-04'),
        updatedAt: null,
        deletedAt: null,
        role: 'superadmin',
    },
    {
        name: 'Ethan Harris',
        email: 'ethan.harris@example.com',
        password: 'ethanpass202',
        createdAt: new Date('2024-01-05'),
        updatedAt: null,
        deletedAt: null,
        role: 'user',
    },
    {
        name: 'Fiona Clark',
        email: 'fiona.clark@example.com',
        password: 'securefiona303',
        createdAt: new Date('2024-01-06'),
        updatedAt: null,
        deletedAt: null,
        role: 'admin',
    },
    {
        name: 'George Lewis',
        email: 'george.lewis@example.com',
        password: 'georgepass404',
        createdAt: new Date('2024-01-07'),
        updatedAt: null,
        deletedAt: null,
        role: 'user',
    },
    {
        name: 'Helen Walker',
        email: 'helen.walker@example.com',
        password: 'stronghelen505',
        createdAt: new Date('2024-01-08'),
        updatedAt: null,
        deletedAt: null,
        role: 'user',
    },
    {
        name: 'Ian Brown',
        email: 'ian.brown@example.com',
        password: 'ianpass606',
        createdAt: new Date('2024-01-09'),
        updatedAt: null,
        deletedAt: null,
        role: 'admin',
    },
    {
        name: 'Julia White',
        email: 'julia.white@example.com',
        password: 'securejulia707',
        createdAt: new Date('2024-01-10'),
        updatedAt: null,
        deletedAt: null,
        role: 'superadmin',
    },
]
