export const categoriesEnum = Object.freeze({
  FOOD: 'food',
  CLOTHES: 'clothes',
  FUEL: 'fuel',
  INSURANCE: 'insurance',
  DEBTS: 'debts',
  ENTERTAINMENT: 'entertainment',
  ENERGY: 'energy',
  HEALTH: 'health',
  TRANSPORT: 'transport',
  EDUCATION: 'education',
  COMMUNICATION: 'communication',
  TAXES: 'taxes',
  OTHERS: 'others',
})
